[[swid-registration]]
== SWID Registration

SWIDs may be registered by the Entity in a "SWID Registry", which is
managed by a "Designated Authority".

The following diagram describes the process of registering a SWID using a "SWID
Registry":

.Process of registering a SWID using a SWID Registry
plantuml_image::../plantuml/registering-a-swid-using-a-swid-registry.puml[]

Note that registration of SWIDs in a registry is an optional step
that is separate from the creation of SWIDs. Most SWIDs will not
be recorded in a centralized registry. SWIDs may be registered in
a system of distributed, decentralized registries. The purpose
of registration is to express membership, and to enable search.

Registration of a SWID returns a Verifiable Credential (VC) that
expresses membership of an Entity in a Domain.

SWIDs are DIDs that can use any DID method, as long as the DIDs fulfill
the requirements in <<swids>>.

* An Entity can "bring its own SWID", which had already been created previously,
according to the applicable DID method's `create` function
(<<DID-REGISTRATION>>).

* If an Entity does not yet have a SWID, the processes of creating and registering
a SWID can be combined in a single flow. In this case, the `did:swid`
DID method MUST be used, which has been specifically designed to meet the requirements
of SWIDs for the Spatial Web. See <<DID-SWID>> for the specification.

To register a SWID in a "SWID Registry", the `execute` function
(<<DID-REGISTRATION>>) is used.

[example]
.Request to register a SWID
====
.HTTP POST to `https:// <swid-registry> /execute`
[source%unnumbered,json]
----
{
  "operation": [
     "addToRegistry"
  ],
  "operationData": [
     {}
  ],
 "did": "did:swid:zQmQoeG7u6XBtdXoek5p3aPoTjaSRemHAKrMcY2Hcjpe3jv#hstp",
  "secret": {},
  "options": {}
}
----
====

[example]
.Response
====
[source%unnumbered,json]
----
{
  "didState": {
    "state": "finished"
  },
  "operationResult": [{
    "membershipCredential": {
       ...
    }
  }]
}
----
====

[example]
.Membership Credential
====
[source%unnumbered]
----
{
  "@context": [
    "https://www.w3.org guy/ns/credentials/v2",
    "https://spatialwebfoundation.org/contexts/registry/"
  ],
  "type": [
    "VerifiableCredential",
    "DomainMembershipCredential"
  ],
  "issuer": {
    "id": "did:web:example.com",
    "type": [
      "Entity",
      "DomainAuthority"
    ]
  },
  "validFrom": "2025-07-01T00:00:00Z",
  "validUntil": "2034-08-31T23:59:59Z",
  "credentialSubject": {
    "id": "did:swid:zQmQoeG7u6XBtdXoek5p3aPoTjaSRemHAKrMcY2Hcjpe3jv",
    "type": [
      "Entity",
      "Domain",
      "Person"
    ],
    "roles": [
      "DomainMember",
      "LoyaltyProgramMember"
    ],
    "abilities": [ ... ]
  },
  "proof": {
    ...
  }
}
----
====

During the process of registering a SWID, the Entity MAY be required to prove
control of its SWID's associated public key, using DID Signing Requests
(<<DID-REGISTRATION>>) and Signing Responses (<<DID-REGISTRATION>>).

[example]
.Signing Request
====
[source%unnumbered]
----
{
	"jobId": "96202012-41d8-424a-85a9-3673bda6abc7",
	"didState": {
		"state": "action",
		"action": "signPayload",
		"signingRequest": {
			"signingRequestRegistration": {
				"kid": "#keys-1",
				"alg": "EdDSA",
				"purpose": "authentication",
				"serializedPayload": "<-- base 64 encoded -->"
			}
		}
	},
	"didRegistrationMetadata": { ... },
	"didDocumentMetadata": { ... }
}
----
====

[example]
.Signing Response
====
[source%unnumbered,json]
----
{
  "jobId": "96202012-41d8-424a-85a9-3673bda6abc7",
  "options": {
    "clientSecretMode": true
  },
  "secret": {
    "signingResponse": {
      "signingRequestRegistration": {
        "signature": "<-- base64 encoded -->"
      }
    }
  },
  "didDocument": {}
}
----
====
